# Use an official Node.js image with development tools
FROM node:19 AS development

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install all dependencies including devDependencies
RUN npm install

# Copy the application files to the working directory
COPY . .

# Expose the default port for development (optional)
EXPOSE 3000

# Define the command to run your application in development
CMD ["npm", "run", "start"]